version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: financialtransactions
      - name: customertypetexts
      - name: productcategorytexts
      - name: glaccounttypetexts
      - name: products
