version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: financial_transactions
      - name: customer_type_texts
      - name: product_category_texts
      - name: gl_account_type_texts
      - name: products
